name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # чтобы actions использовали Node.js 24

jobs:

  sast:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Bandit
        run: pip install bandit

      - name: Run SAST
        run: |
          bandit -r app -f json -o report.json || true

      - name: Security Gate
        run: |
          if grep -q '"issue_severity": "HIGH"' report.json; then
             grep -q '"issue_severity": "MEDIUM"' report.json; then
            echo "❌ High vulnerability found"
            exit 1
          else
            echo "✅ No high vulnerabilities"
          fi

  deploy:
    runs-on: ubuntu-latest  # теперь тоже GitHub-hosted
    needs: sast

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker
        run: docker build -t myapp .

      - name: Stop old container
        run: docker stop myapp || true

      - name: Remove old container
        run: docker rm myapp || true

      - name: Run container
        run: docker run -d -p 8000:8000 --name myapp myapp
